# Generated by Django 4.2.6 on 2024-01-01 08:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=1000)),
                ('status', models.CharField(choices=[('Used', 'USED'), ('New', 'NEW')], default='used', max_length=10)),
                ('model_year', models.CharField(blank=True, max_length=4, null=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(blank=True, choices=[('Manual', 'Automatic'), ('Manual', 'Manual')], max_length=10, null=True)),
                ('body', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Heavy Truck', 'Heavy Truck')], max_length=15, null=True)),
                ('drive_train', models.CharField(blank=True, choices=[('All Wheel', 'All Wheel'), ('Front Wheel', 'Front Wheel'), ('Rear Wheel', 'Rear Wheel')], max_length=20, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('auxilliary', models.BooleanField(default=False)),
                ('cylinders', models.IntegerField(blank=True, choices=[(4, 4), (6, 6), (8, 8), (12, 12)], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=14)),
                ('message', models.CharField(default='Hello', max_length=1024)),
                ('mail', models.EmailField(default='oluwatimileyin962@gmail.com', max_length=254)),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nnaezitech.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='nnaezitech.company'),
        ),
    ]
