# Generated by Django 4.2.6 on 2024-01-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnaezitech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
